# Generated by Django 5.1.1 on 2025-10-11 15:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('seats', models.PositiveIntegerField(default=4)),
                ('luggage_capacity', models.PositiveIntegerField(default=2)),
                ('location', models.CharField(max_length=255)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['company', 'model'],
            },
        ),
        migrations.CreateModel(
            name='CarAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='cars.car')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('car', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(editable=False, max_length=18, unique=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('settled', 'Settled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=64)),
                ('contact_email', models.EmailField(max_length=254)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference_number'], name='cars_carboo_referen_0b21e1_idx')],
            },
        ),
    ]
